### ISSUE TITLE
HTTPS Everywhere blocks site from loading

### ISSUE THREAD

**Issue by ericgoedtel** [clarabstract/factorio-calc#22]
Your JS for the GitHub page is served from a non-HTTPS-enabled CDN so the mixed security content will be blocked by most browsers. Can you move to HTTP-only or enable HTTPS for the CDN?

**Comment by cdhowie** [comment]
@ericgoedtel Is this still a problem? I checked in Chrome and the assets all appear to be loaded over HTTPS now.

**Comment by ericgoedtel** [comment]
👍
