### ISSUE TITLE
Interested in my changes?

### ISSUE THREAD

**Issue by abrindam** [clarabstract/factorio-calc#38]
Hey there! This tool is super awesome. I thought it was such a good idea that I forked it and added some features. Unfortunately along the way I got overly enthusiastic and refactored a good deal of the code as well, so there is a bit of a massive diff.

With this in mind, I wanted to give you the option of merging my changes back into mainline. No pressure! I did add a bunch of features, some of which are already issues here. I thought you might be receptive given this project appears to mostly be in maintenance mode. However, if you feel uncomfortable accepting massive pull requests, I would totally get that too.

It's over at https://github.com/abrindam/factorio-calc (and thus https://abrindam.github.io/factorio-calc/).

Major features added:
- Support for adding multiple recipes, which all then contribute to the main total
- UI cleanup to make it more readable
- "Explain" function that tries to educate the user on how the tool arrived at the numbers
- Bulk Import/Export. Enter multiple recipes as text, which you can then save locally as a text field
- Add support for calculating the number of miners needed for ore

Refactoring work:
- Separate UI into multiple files (one per React component)
- Move majority of calculations into JS to minimize Lua dependency (Lua just provides data to JS)
- Upgrade React to latest

**Comment by arkottke** [comment]
I don't see that your updated website is working.

**Comment by abrindam** [comment]
Took a look, appears my changes have broken IE somehow. Is that what you're using? If not, can you be more specific, e.g. add some console logs?

I'll look into the IE issue. Unfortunately I'm a Mac user so I missed that.

**Comment by arkottke** [comment]
I am using Chrome on Linux. That appears to have fixed my issue.

**Comment by abrindam** [comment]
Excellent! I'll look into the IE issue in the near future.

**Comment by arkottke** [comment]
@abrindam I think there is something strange with your code with it reporting 1 assembler for every recipe:
![image](https://cloud.githubusercontent.com/assets/1033651/25442128/0984f268-2a59-11e7-8be0-29aa1345c4a8.png)
This is the same for the rubyruy version:
![image](https://cloud.githubusercontent.com/assets/1033651/25442145/1659c25c-2a59-11e7-99a9-c1de0cf17ce1.png)

Also, the width of the flow chart should be made dynamic -- it cuts off information for `science-pack-3` recipes.
![image](https://cloud.githubusercontent.com/assets/1033651/25442200/4399c6ea-2a59-11e7-9a6d-2328be9bb851.png)

**Comment by abrindam** [comment]
@arkottke  my version uses items/minute while the original uses items/sec. I chose to go to items/minute because 1 item/sec can actually be a lot of items, so items/min gives better granularity without having to resort to decimals. Also, the production stats show items/min in game, so you can more easily compare.

If you put 60 items/min into my tool, you'll get the same results as putting 1 item/sec into the original.

On the flow chart, agreed, but it's a pre-existing issue :-)

**Comment by abrindam** [comment]
@arkottke FYI I just pushed some changes that fixed the issues I was seeing with IE. If you wanted to check it out with whatever original browser you had problems with, it would be much appreciated!

**Comment by abrindam** [comment]
I just added support for 0.15.x to my fork, by combining the work of "folk" from the forums, my own work, and the 0.15.2 pull request from shouya (https://github.com/rubyruy/factorio-calc/pull/39).

It proved to be quite easy to add the support with my refactored code, while it seems others were struggling to add it to the existing.

I'm going to add a formal pull request now that there's a definite benefit to the community. If I don't hear back in a few days, I'll share a link to my fork in the forums. I'd like to avoid this and keep the rubyruy "brand" going forward!

**Comment by abrindam** [comment]
@arkottke FYI I just fixed the flow chart issue. Give it a try and let me know what you think!

**Comment by arkottke** [comment]
@abrindam Now the flow chart is not showing for me on Chrome on Window --
it just shows as an empty box.

**Comment by abrindam** [comment]
Further discussion tracked in #40 .
