### ISSUE TITLE
Default to Assembler Machine 2 & Steel/Electric Furnace?

### ISSUE THREAD

**Issue by abrindam** [clarabstract/factorio-calc#42]
Theory: by the time a player is at the scale at which this tool is useful, they likely are using at least Assembler Machine 2 and Steel Furnaces. Assembler Machine 1 and Stone Furnaces are for chumps :-)

I took a spin through the "Show Your Creations" section of the Factorio forum and everything I saw used Assembling Machine 2, and either Steel or Electric Furnaces.

On the other hand, it seems there is a lot of variance on belts used so I would suggest sticking to the normal belts by default.

Thoughts?

**Comment by odegroot** [comment]
See PR https://github.com/rubyruy/factorio-calc/pull/49. It's related, but does not completely resolve this issue.

**Comment by abrindam** [comment]
I had also had the idea to do this, but forgot to mention it in the above. Awesome!

I'll close this as I think PR #49 is good enough.
